### ISSUE TITLE
Could not load lookup=LOOKUP-event_type_lookup

### ISSUE THREAD

**Issue by MartijnSF** [mbegan/Okta-Identity-Cloud-for-Splunk#37]
After upgrading from 2.25.19 to the new 2.25.21 release we are getting this error every search.

Could not load lookup=LOOKUP-event_type_lookup

It looks like an automatic lookup fails.

**Splunk Cloud 8.2.2107.1.**

Thanks in advance!
Martijn

**Comment by s-m-p** [comment]
Is the lookup definition exported to your app context? Do you have
permission to read the app, lookup definition and lookup file?

**Comment by MartijnSF** [comment]
It's solved by Splunk support.

They closed the ticket with the following note:

_This issue was caused by the fact that the Splunk could not load the lookup file LOOKUP-event_type_lookup, due to not finding destination field change_type. It seems the upgrade was not done successfully and the file was not updated with the new definition._
