### ISSUE TITLE
Include tenant in the json data

### ISSUE THREAD

**Issue by ncrowleysalesforce** [mbegan/Okta-Identity-Cloud-for-Splunk#43]
Hi, we're forwarding Okta logs from 3 different tenants to Security. Because the host metadata is lost when forwarding a copy of the log, they don't know which tenant the logs came from. Could the tenant be included in every log object?

Is there any workaround in the meantime?

**Comment by mbegan** [comment]
The “host” attribute is populated with the Okta tenant name.

**Comment by ncrowleysalesforce** [comment]
The host metadata can be used in Splunk, but it's lost when the event is forwarded to a non-Splunk 3rd party because the tenant/host is not in the JSON object. When events from multiple tenants are forwarded, there is no way for the receiving party to tell which tenant they came from.

We have opened a feature request with Okta to include the tenant id in the events. Also, we have a couple of different workarounds which will allow us to progress while waiting for the feature request.

Anyway, I'm not sure the add-on is the correct place to fix this problem, so I'll close this issue.
